# Generated by Django 3.2.5 on 2021-07-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_name',
            new_name='name',
        ),
    ]
