# Generated by Django 3.2.5 on 2021-07-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210722_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Netflix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(max_length=100)),
                ('show_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('date_added', models.DateField()),
                ('release_year', models.IntegerField()),
                ('rating', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('listed_in', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
