# Generated by Django 3.2.5 on 2021-07-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210723_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflix',
            name='release_year',
            field=models.IntegerField(max_length=100),
        ),
    ]
