# Generated by Django 3.2.5 on 2021-07-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_planet'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='auto',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='bike',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='bus',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='car',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='taxi',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
